name: main

on:
  pull_request: 
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@b80ff79f1755d06ba70441c368a6fe801f5f3a62

      - name: Node Setup
        uses: actions/setup-node@eff380dfbcf941bf8832e4acb788cebe13dfd758
        with:
          node-version: 18

      - name: Install depemdencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Cypress Tests
        run: npm run test
